services:
  bind9:
    image: ubuntu/bind9:9.18-24.04_beta
    container_name: bind9
    restart: unless-stopped
    environment:
      - TZ=UTC
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
